CREATE TABLE IF NOT EXISTS Authority (
  Authority_ID INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(255) NOT NULL,
  Designation VARCHAR(255) NOT NULL,
  Control_Room VARCHAR(255) NOT NULL,
  Works_Under INT NULL,
  FOREIGN KEY (Works_Under) REFERENCES Authority(Authority_ID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS Vehicle (
  Vehicle_ID INT AUTO_INCREMENT PRIMARY KEY,
  Vehicle_Number VARCHAR(255) NOT NULL,
  Vehicle_Type VARCHAR(255) NOT NULL,
  Manufacturer VARCHAR(255) NOT NULL,
  Assigned_Location VARCHAR(255) NOT NULL,
  Authority_ID INT NULL,
  FOREIGN KEY (Authority_ID) REFERENCES Authority(Authority_ID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS Driver (
  Driver_ID INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(255) NOT NULL,
  Address VARCHAR(255) NOT NULL,
  Control_Number VARCHAR(255) NOT NULL,
  Duty_Per_Order_ID INT NULL,
  Vehicle_ID INT NULL,
  Authority_ID INT NULL,
  FOREIGN KEY (Vehicle_ID) REFERENCES Vehicle(Vehicle_ID) ON DELETE SET NULL,
  FOREIGN KEY (Authority_ID) REFERENCES Authority(Authority_ID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS Bin (
  Bin_ID INT AUTO_INCREMENT PRIMARY KEY,
  Capacity INT NOT NULL,
  GSM_Number VARCHAR(255) NOT NULL,
  Installation_Date DATE NOT NULL,
  Assigned_Location VARCHAR(255) NOT NULL,
  Vehicle_ID INT NULL,
  Authority_ID INT NULL,
  FOREIGN KEY (Vehicle_ID) REFERENCES Vehicle(Vehicle_ID) ON DELETE SET NULL,
  FOREIGN KEY (Authority_ID) REFERENCES Authority(Authority_ID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS UserTable (
  User_ID INT AUTO_INCREMENT PRIMARY KEY,
  Username VARCHAR(255) UNIQUE NULL,
  Password_Hash VARCHAR(255) NULL,
  Mobile_Number VARCHAR(20) NULL,
  House_Number VARCHAR(255) NULL,
  Vehicle_ID INT NULL,
  FOREIGN KEY (Vehicle_ID) REFERENCES Vehicle(Vehicle_ID) ON DELETE SET NULL
);
